/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.54).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.CargoContainer;
import io.swagger.model.NewCargoContainer;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2024-04-01T19:16:46.028037-04:00[America/New_York]")
@Validated
public interface CargoContainersApi {

    @Operation(summary = "Delete a specific cargo container by ID", description = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "204", description = "Cargo container deleted successfully") })
    @RequestMapping(value = "/cargo-containers/{container_id}",
        method = RequestMethod.DELETE)
    ResponseEntity<Void> cargoContainersContainerIdDelete(@Parameter(in = ParameterIn.PATH, description = "ID of the cargo container to delete", required=true, schema=@Schema()) @PathVariable("container_id") String containerId
);


    @Operation(summary = "Get a specific cargo container by ID", description = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Cargo container details", content = @Content(mediaType = "application/json", schema = @Schema(implementation = CargoContainer.class))) })
    @RequestMapping(value = "/cargo-containers/{container_id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<CargoContainer> cargoContainersContainerIdGet(@Parameter(in = ParameterIn.PATH, description = "ID of the cargo container to retrieve", required=true, schema=@Schema()) @PathVariable("container_id") String containerId
);


    @Operation(summary = "Update a specific cargo container by ID", description = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Cargo container updated successfully", content = @Content(mediaType = "application/json", schema = @Schema(implementation = CargoContainer.class))) })
    @RequestMapping(value = "/cargo-containers/{container_id}",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.PUT)
    ResponseEntity<CargoContainer> cargoContainersContainerIdPut(@Parameter(in = ParameterIn.PATH, description = "ID of the cargo container to update", required=true, schema=@Schema()) @PathVariable("container_id") String containerId
, @Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody NewCargoContainer body
);


    @Operation(summary = "Get all cargo containers", description = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "List of cargo containers", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = CargoContainer.class)))) })
    @RequestMapping(value = "/cargo-containers",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<CargoContainer>> cargoContainersGet(@Parameter(in = ParameterIn.QUERY, description = "Filter cargo containers by status" ,schema=@Schema()) @Valid @RequestParam(value = "status", required = false) String status
, @Parameter(in = ParameterIn.QUERY, description = "Limit the number of results returned. Default is 10." ,schema=@Schema()) @Valid @RequestParam(value = "limit", required = false) Integer limit
, @Parameter(in = ParameterIn.QUERY, description = "Offset the results returned for pagination" ,schema=@Schema()) @Valid @RequestParam(value = "offset", required = false) Integer offset
);


    @Operation(summary = "Create a new cargo container", description = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "Cargo container created successfully", content = @Content(mediaType = "application/json", schema = @Schema(implementation = CargoContainer.class))) })
    @RequestMapping(value = "/cargo-containers",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<CargoContainer> cargoContainersPost(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody NewCargoContainer body
);

}

