/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.54).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Luggage;
import io.swagger.model.NewLuggage;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2024-04-01T19:16:46.028037-04:00[America/New_York]")
@Validated
public interface LuggageApi {

    @Operation(summary = "Get all luggage items", description = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "List of luggage items", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Luggage.class)))) })
    @RequestMapping(value = "/luggage",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<Luggage>> luggageGet(@Parameter(in = ParameterIn.QUERY, description = "Filter luggage items by status" ,schema=@Schema()) @Valid @RequestParam(value = "status", required = false) String status
, @Parameter(in = ParameterIn.QUERY, description = "Filter luggage items by container ID" ,schema=@Schema()) @Valid @RequestParam(value = "container_id", required = false) String containerId
, @Parameter(in = ParameterIn.QUERY, description = "Limit the number of results returned. Default is 10." ,schema=@Schema()) @Valid @RequestParam(value = "limit", required = false) Integer limit
, @Parameter(in = ParameterIn.QUERY, description = "Offset the results returned for pagination" ,schema=@Schema()) @Valid @RequestParam(value = "offset", required = false) Integer offset
);


    @Operation(summary = "Create a new luggage item", description = "", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "201", description = "Luggage item created successfully", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Luggage.class))) })
    @RequestMapping(value = "/luggage",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<Luggage> luggagePost(@Parameter(in = ParameterIn.DEFAULT, description = "", required=true, schema=@Schema()) @Valid @RequestBody NewLuggage body
);

}

